layout_spectrum: 0.6443060887977481
typography_spectrum: 0.8297374632675201
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.15818422357551754
  lightness: 0.0803833301179111
  saturation: 0.3544388781301677
  rhythmicContrast: 0.41578734409995377
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Shakalaka!
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Not your average promoter
description: We want to blow your mind
purpose: []
