typography_spectrum: 0.7211985348258168
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3787286588922143
  lightness: 0.6091073516290635
  saturation: 0.19614605675451458
  rhythmicContrast: 0.17164434911683202
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50675
analytics:
  google: null
  facebook: null
  twitter: null
name: Shakalaka!
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Culture & Entertainment Promoters
purpose: []
